{**
 * TreeView - Nette Framework Example.
 *
 * @copyright  Copyright (c) 2010 Roman Novák
 * @package    nette-treeview
 *
 * @param string   $basePath web base path
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param array    $flashes  flash messages
 *}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="TreeView - Nette Framework Example">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>TreeView - Nette Framework Example</title>

	<script type="text/javascript" src="{$basePath}/js/jquery-ui-1.7.2.custom/js/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery-ui-1.7.2.custom/js/jquery-ui-1.7.2.custom.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>

	<script type="text/javascript">
	    $("a.ajax").live("click", function (event) {
		event.preventDefault();
		$.get(this.href);
	    });
	</script>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/js/jquery-ui-1.7.2.custom/css/ui-lightness/jquery-ui-1.7.2.custom.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">

	<style type="text/css">
		body {
			margin: 0;
			padding 0;
		}
	
		div {
			padding: .2em 1em;
		}
	
		#header {
			background: #EEE;
			border-bottom: 1px #DDD solid;
		}
	
		h1 {
			color: #0056ad;
			font-size: 30px;
		}
	
		h2 {
			color: gray;
			font-size: 20px;
		}
		
		.active {
			font-weight: bold;
		}
		
	    ul li {
		margin: 0px;
		padding: 0px;
		list-style-type: none;
		line-height: 16px;
	    }

	    a {
		text-decoration: none;
		color: #000;
	    }

	    a:hover {
		text-decoration: underline;
	    }
	</style>
</head>

<body>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	@{include #content}
</body>
</html>
